import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowUpRight } from 'lucide-react'
import { services, categoryMeta, type CategoryKey } from '@/data/services'
import Button from '@/components/ui/Button'
const order:CategoryKey[]=['it-solutions','business-software','ai-automation','software-engineering']
const visual:{[K in CategoryKey]:string}={
 'it-solutions':'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1800&q=85',
 'business-software':'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1800&q=85',
 'ai-automation':'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1800&q=85',
 'software-engineering':'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1800&q=85',
}
export default function Solutions(){return <><section className="bg-ink text-white py-20 lg:py-28 relative overflow-hidden"><div className="absolute inset-0 dark-grid opacity-60"/><div className="container-a relative"><p className="eyebrow mb-5">CAPABILITIES</p><h1 className="h-display text-5xl sm:text-6xl lg:text-7xl max-w-4xl text-balance">The right mix of technology for the work you actually do.</h1><p className="text-white/50 text-lg leading-8 max-w-2xl mt-7">Explore the capabilities below. Services can stand alone, but the strongest results usually come from connecting a few of them around one business problem.</p></div></section>{order.map((cat,idx)=>{const meta=categoryMeta[cat],items=services.filter(s=>s.category===cat);return <section key={cat} id={meta.anchor} className="bg-paper py-20 lg:py-28 border-b border-lineDark scroll-mt-20"><div className="container-a"><div className="grid lg:grid-cols-[.65fr_1.35fr] gap-10 lg:gap-20 items-start mb-12"><div><span className="font-mono text-[10px] text-mutedDark">0{idx+1} / {items.length} services</span><h2 className="h-display text-3xl sm:text-4xl mt-4">{meta.label}</h2></div><p className="text-mutedDark leading-7 max-w-2xl">{meta.description}</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{items.map((s,i)=><motion.div key={s.slug} initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-40px'}} transition={{duration:.35,delay:i*.025}}><Link to={`/solutions/${s.slug}`} className="group block h-full rounded-2xl border border-lineDark bg-white overflow-hidden card-hover"><div className="relative h-36 overflow-hidden"><img src={visual[cat]} alt="" className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-ink/65 to-transparent"/><span className="absolute bottom-3 left-4 font-mono text-[9px] uppercase tracking-[.18em] text-white/70">{meta.label}</span></div><div className="p-6"><h3 className="font-display text-xl">{s.name}</h3><p className="text-mutedDark text-sm leading-6 mt-2 min-h-[72px]">{s.tagline}</p><span className="inline-flex items-center gap-2 mt-5 text-xs font-medium">Explore <ArrowUpRight size={14} className="text-signal group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform"/></span></div></Link></motion.div>)}</div></div></section>})}<section className="bg-[#11192b] py-24 text-center"><div className="container-a"><p className="eyebrow mb-5">NEED A STARTING POINT?</p><h2 className="h-display text-white text-4xl sm:text-5xl max-w-3xl mx-auto">Bring us the problem. We'll help you shape the solution.</h2><div className="flex justify-center mt-9"><Button to="/contact">Start a conversation</Button></div></div></section></>}
